In [2]:
import numpy as np
import pandas as pd
import random

In [3]:
#initializing the Agent Matrix
agent = np.array ([[-1,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                   [0,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  [0,-1,-1,0,-1,-1,-1,-1,-1,-1,0,-1,-1,-1],
                   [-1,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,0,-1],
                  [-1,-1,-1,0,-1,0,0,-1,-1,-1,-1,-1,-1,-1],
                    [-1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,0],
                     [-1,-1,-1,-1,0,-1,-1,0,-1,-1,-1,-1,0,-1],
                   [-1,-1,-1,-1,-1,0,0,-1,100,-1,-1,0,-1,-1],
                   [-1,-1,-1,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1],
                    [-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,-1],
                    [-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,0,-1,-1],
                   [-1,-1,-1,-1,-1,-1,-1,0,-1,-1,0,-1,-1,-1],
                   [-1,-1,-1,0,-1,-1,0,-1,-1,0,-1,-1,-1,-1],
                   [-1,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1]])

In [11]:
pd.DataFrame(agent)
#Column Represents 0=>A ,1=>B , 2=>C, 3=>D, 4=>E , 5=>F , 6=>G
#7=>H , 8=>I , 9=>J , 10=>K , 11=>L ,12=>M , 13=>N

0   1   2   3   4   5   6   7    8   9   10  11  12  13
0   -1   0   0  -1  -1  -1  -1  -1   -1  -1  -1  -1  -1  -1
1    0  -1  -1   0  -1  -1  -1  -1   -1  -1  -1  -1  -1  -1
2    0  -1  -1   0  -1  -1  -1  -1   -1  -1   0  -1  -1  -1
3   -1   0   0  -1   0  -1  -1  -1   -1  -1  -1  -1   0  -1
4   -1  -1  -1   0  -1   0   0  -1   -1  -1  -1  -1  -1  -1
5   -1  -1  -1  -1   0  -1  -1  -1   -1  -1  -1  -1  -1   0
6   -1  -1  -1  -1   0  -1  -1   0   -1  -1  -1  -1   0  -1
7   -1  -1  -1  -1  -1   0   0  -1  100  -1  -1   0  -1  -1
8   -1  -1  -1  -1  -1  -1  -1   0   -1  -1  -1  -1  -1  -1
9   -1  -1  -1  -1  -1  -1  -1  -1   -1  -1  -1  -1   0  -1
10  -1  -1   0  -1  -1  -1  -1  -1   -1  -1  -1   0  -1  -1
11  -1  -1  -1  -1  -1  -1  -1   0   -1  -1   0  -1  -1  -1
12  -1  -1  -1   0  -1  -1   0  -1   -1   0  -1  -1  -1  -1
13  -1  -1  -1  -1  -1   0  -1  -1   -1  -1  -1  -1  -1  -1

In [5]:
# Creating a 14x14 matrix with 0 to initialzing the Q Table
def initialize_q(m,n):
    return np.zeros((m,n))

#Using Pands for Display Purpose
qmatrix = initialize_q(14,14)
pd.DataFrame(qmatrix)


0    1    2    3    4    5    6    7    8    9    10   11   12   13
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
12  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [13]:
#denoting rooms as 6 according to problem
def set_initial_state(rooms =14):
    
    #Store the initial State
    return np.random.randint(0, rooms)

#initializing the action to be implement from the matrix
def get_action(current_state, agent_mat):
    
    #Given a State, Choose from the Possiable
    valid_actions = []
    for action in enumerate(agent_mat[current_state]):
        if action[1] !=-1:
            valid_actions +=[action[0]]
    return random.choice(valid_actions)

def take_act(current_state, agent_mat,gamma, verbose = False):
    
    #Take a Single Action
    action = get_action(current_state, agent_mat)
    sa_reward= agent_mat[current_state,action] #Current State-action Reward
    ns_reward= max(qmatrix[action,]) #Next State-action Reward
    print(ns_reward)
    q_cur_state = sa_reward + (gamma * ns_reward) #Current state will be updated with the actions done 
    qmatrix[current_state, action] = q_cur_state #  Mutates q Matrix
    new_state = action
    if verbose:
        print(qmatrix)
        print(f"Old State: {current_state} | New State : {new_state}\n\n")
        if new_state == 8:   #When new State get to room 8 (I point) , Agent will stop the traversal 
            print(f" Agent Has Reached their Goal !!! ")
    return new_state


In [12]:
def initial_episode(agent_mat,initial_state, gamma, verbose =False):
    
    # Runs 1 episode (or Simulation) until the agent reach it's goal-state
    
    current_state = initial_state
    while True: # We won't use current state == 8 because possiable to initialize in 8
        current_state = take_act(current_state, agent_mat, gamma , verbose)
        if current_state == 8:
            break
                                    
def train_agent(iteration , agent_mat , gamma , verbose: False): #Training the agent for q-learning
        
        #Runs a given number of episodes then normalize the matrix
        print("Training in Progress>>>>")
        for episode in range(iteration):
            initial_state = set_initial_state()
            initial_episode(agent_mat, initial_state, gamma, verbose)
        print("Training Complete! >>")
        
        return qmatrix

In [14]:
#Normalizing the q matrix for get a simplified 2D table
def normalize_mat(qmatrix):
    normalized_q=qmatrix / max(qmatrix[qmatrix.nonzero()])*100
    return normalized_q.astype(int)

In [16]:
# Test Run of Single Episode
gamma = 0.1
initial_state = 9
initial_action = get_action(initial_state, agent)

initial_episode(agent, initial_state, gamma, True)

0.0
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 100.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0. 

In [17]:
#Test Run Full Training  (Training= 1500 iterations)
gamma = 0.8
initial_state=set_initial_state()
initial_action = get_action(initial_state, agent)

q_table = train_agent(1500, agent, gamma, False)

# Creating DataFrame for Display Purpose
pd.DataFrame(q_table)

Training in Progress>>>>
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.8
0.0
0.8
1.0
0.8
0.0
0.0
0.0
0.0
0.0
10.0
100.0
0.0
100.0
80.0
80.0
164.0
80.0
1.0
80.0
164.0
131.20000000000002
64.0
0.8
0.6400000000000001
0.8
0.6400000000000001
0.8
64.0
0.8
0.0
0.8
8.0
131.20000000000002
164.0
0.0
0.0
0.0
0.0
0.6400000000000001
0.5120000000000001
0.0
164.0
131.20000000000002
164.0
131.20000000000002
0.0
0.6400000000000001
0.5120000000000001
0.6400000000000001
0.5120000000000001
0.6400000000000001
6.4
5.120000000000001
0.5120000000000001
131.20000000000002
104.96000000000002
5.120000000000001
0.5120000000000001
5.120000000000001
6.4
104.96000000000002
83.96800000000002
5.120000000000001
83.96800000000002
104.96000000000002
131.20000000000002
104.96000000000002
131.20000000000002
204.96000000000004
131.20000000000002
51.2
64.0
83.96800000000002
104.96000000000002
83.96800000000002
67.17440000000002
83.96800000000002
67.17440000000002
83.96800000000002
1

0          1           2           3           4           5   \
0    0.000000  91.022222  113.777778    0.000000    0.000000    0.000000   
1   91.022222   0.000000    0.000000  113.777778    0.000000    0.000000   
2   91.022222   0.000000    0.000000  113.777778    0.000000    0.000000   
3    0.000000  91.022222  113.777778    0.000000  142.222222    0.000000   
4    0.000000   0.000000    0.000000  113.777778    0.000000  113.777778   
5    0.000000   0.000000    0.000000    0.000000  142.222222    0.000000   
6    0.000000   0.000000    0.000000    0.000000  142.222222    0.000000   
7    0.000000   0.000000    0.000000    0.000000    0.000000  113.777778   
8    0.000000   0.000000    0.000000    0.000000    0.000000    0.000000   
9    0.000000   0.000000    0.000000    0.000000    0.000000    0.000000   
10   0.000000   0.000000  113.777778    0.000000    0.000000    0.000000   
11   0.000000   0.000000    0.000000    0.000000    0.000000    0.000000   
12   0.000000   0.000000    0.000000  113.777778    0.000000    0.000000   
13   0.000000   0.000000    0.000000    0.000000    0.000000  113.777778   

            6           7           8           9           10          11  \
0     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
1     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
2     0.000000    0.000000    0.000000    0.000000  142.222222    0.000000   
3     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
4   177.777778    0.000000    0.000000    0.000000    0.000000    0.000000   
5     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
6     0.000000  222.222222    0.000000    0.000000    0.000000    0.000000   
7   177.777778    0.000000  277.777778    0.000000    0.000000  177.777778   
8     0.000000  222.222222    0.000000    0.000000    0.000000    0.000000   
9     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
10    0.000000    0.000000    0.000000    0.000000    0.000000  177.777778   
11    0.000000  222.222222    0.000000    0.000000  142.222222    0.000000   
12  177.777778    0.000000    0.000000  113.777778    0.000000    0.000000   
13    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   

            12         13  
0     0.000000   0.000000  
1     0.000000   0.000000  
2     0.000000   0.000000  
3   142.222222   0.000000  
4     0.000000   0.000000  
5     0.000000  91.022222  
6   142.222222   0.000000  
7     0.000000   0.000000  
8     0.000000   0.000000  
9   142.222222   0.000000  
10    0.000000   0.000000  
11    0.000000   0.000000  
12    0.000000   0.000000  
13    0.000000   0.000000

In [18]:
#Normalizing the Dataframe

pd.DataFrame(normalize_mat(q_table))

0   1   2   3   4   5   6   7    8   9   10  11  12  13
0    0  32  40   0   0   0   0   0    0   0   0   0   0   0
1   32   0   0  40   0   0   0   0    0   0   0   0   0   0
2   32   0   0  40   0   0   0   0    0   0  51   0   0   0
3    0  32  40   0  51   0   0   0    0   0   0   0  51   0
4    0   0   0  40   0  40  64   0    0   0   0   0   0   0
5    0   0   0   0  51   0   0   0    0   0   0   0   0  32
6    0   0   0   0  51   0   0  80    0   0   0   0  51   0
7    0   0   0   0   0  40  64   0  100   0   0  64   0   0
8    0   0   0   0   0   0   0  80    0   0   0   0   0   0
9    0   0   0   0   0   0   0   0    0   0   0   0  51   0
10   0   0  40   0   0   0   0   0    0   0   0  64   0   0
11   0   0   0   0   0   0   0  80    0   0  51   0   0   0
12   0   0   0  40   0   0  64   0    0  40   0   0   0   0
13   0   0   0   0   0  40   0   0    0   0   0   0   0   0

In [24]:
#After the training is done , we deploy the agent from this agent
def deploy_agent(init_state, q_table):
    print("Start:\n",init_state)
    state = init_state
    steps =0
    while True:
        steps += 1
        action = np.argmax(q_table[state,:])  # Filtering out the maximum values from the normalized q Table
        print(action)
        state= action
        if action == 8:
            print("Finished the Searching")
            return steps

In [25]:
#Column Represents 0=>A ,1=>B , 2=>C, 3=>D, 4=>E , 5=>F , 6=>G
#7=>H , 8=>I , 9=>J , 10=>K , 11=>L ,12=>M , 13=>N

#Lets Run an Example 1
start_room = 9  #insert the Starting room for agent to start
steps = deploy_agent(start_room,q_table)
print("Number of Rooms/ Actions: ", steps)

Start: 
 9
12
6
7
8
Finished the Searching
Number of Rooms/ Actions:  4


In [26]:
#Column Represents 0=>A ,1=>B , 2=>C, 3=>D, 4=>E , 5=>F , 6=>G
#7=>H , 8=>I , 9=>J , 10=>K , 11=>L ,12=>M , 13=>N

#Lets Run an Example 2
start_room = 4  #insert the Starting room for agent to start
steps = deploy_agent(start_room,q_table)
print("Number of Rooms/ Actions: ", steps)

Start: 
 4
6
7
8
Finished the Searching
Number of Rooms/ Actions:  3
