Write a python program that read data from the given ‘data.csv’ file to a numpy array and do given tasks
1.1.	Covert the values into integer
1.2.	Display the array
1.3.	Display all the values in first row
1.4.	Display all the values in last row
1.5.	Display values in rows from 5th to 9th and columns 1st and 2nd
1.6.	Create three arrays a, b, c by separating three columns
1.7.	Add 5 to all the values in the array a
1.8.	Add each value in array a to each value in array b and display the answers
1.9.	Calculate and display Total, mean, standard deviation, maximum value, and minimum value for the values in array c
1.10.	Reshape the arrays a and b as 4 x 4 arrays
1.11.	Calculate and display a product b
1.12.	Display only the values that is less than 40 from array c
1.13.	Calculate and display total of each row in array a


### Python Program to Read Data and Perform Operations

In [2]:
import numpy as np

# Reading the data from 'dataset.csv' into a numpy array
data = np.genfromtxt('Tutorial(dataset).csv', delimiter=',', skip_header=1).astype(int)

# Display the array
print("Array:\n", data)

# Display all the values in the first row
print("\nFirst row:", data[0])

# Display all the values in the last row
print("\nLast row:", data[-1])

# Display values in rows from 5th to 9th and columns 1st and 2nd
print("\nRows 5th to 9th, Columns 1st and 2nd:\n", data[4:9, 0:2])

# Create three arrays a, b, c by separating three columns
a = data[:, 0]
b = data[:, 1]
c = data[:, 2]

# Add 5 to all the values in array a
a_plus_5 = a + 5
print("\nArray 'a' after adding 5:\n", a_plus_5)

# Add each value in array a to each value in array b and display the answers
a_plus_b = a + b
print("\nArray 'a + b':\n", a_plus_b)

# Calculate and display total, mean, standard deviation, maximum value, and minimum value for the values in array c
total_c = np.sum(c)
mean_c = np.mean(c)
std_dev_c = np.std(c)
max_c = np.max(c)
min_c = np.min(c)

print("\nArray 'c' statistics:")
print("Total:", total_c)
print("Mean:", mean_c)
print("Standard Deviation:", std_dev_c)
print("Maximum Value:", max_c)
print("Minimum Value:", min_c)

Array:
 [[42  2 33]
 [27 18 16]
 [ 5 19 28]
 [33 49 36]
 [24  5 39]
 [31  2 11]
 [16 28 48]
 [38 29 50]
 [41  5 39]
 [19 36 20]
 [31 28 45]
 [25 11 14]
 [45 32 50]
 [33 34 15]
 [33 28 43]]

First row: [42  2 33]

Last row: [33 28 43]

Rows 5th to 9th, Columns 1st and 2nd:
 [[24  5]
 [31  2]
 [16 28]
 [38 29]
 [41  5]]

Array 'a' after adding 5:
 [47 32 10 38 29 36 21 43 46 24 36 30 50 38 38]

Array 'a + b':
 [44 45 24 82 29 33 44 67 46 55 59 36 77 67 61]

Array 'c' statistics:
Total: 487
Mean: 32.46666666666667
Standard Deviation: 13.60326758131622
Maximum Value: 50
Minimum Value: 11


# Reshape the arrays a and b as 4x4 arrays
a_reshaped = a[:16].reshape(4, 4)
b_reshaped = b[:16].reshape(4, 4)

print("\nReshaped Array 'a':\n", a_reshaped)
print("\nReshaped Array 'b':\n", b_reshaped)

# Calculate and display the product of arrays a and b
product_ab = np.dot(a_reshaped, b_reshaped)
print("\nProduct of reshaped arrays 'a' and 'b':\n", product_ab)

# Display only the values that are less than 40 from array c
c_less_than_40 = c[c < 40]
print("\nValues less than 40 in array 'c':", c_less_than_40)

# Calculate and display the total of each row in array a
row_totals_a = np.sum(a_reshaped, axis=1)
print("\nTotal of each row in reshaped array 'a':", row_totals_a)

### Additional

In [5]:
# Determine the size needed for reshaping
reshape_size = int(np.sqrt(len(a)))

# Reshape the arrays a and b based on the reshape_size
if reshape_size**2 == len(a):  # Check if perfect square
    a_reshaped = a.reshape(reshape_size, reshape_size)
    b_reshaped = b.reshape(reshape_size, reshape_size)
    print("\nReshaped Array 'a':\n", a_reshaped)
    print("\nReshaped Array 'b':\n", b_reshaped)

    # Calculate and display the product of arrays a and b
    product_ab = np.dot(a_reshaped, b_reshaped)
    print("\nProduct of reshaped arrays 'a' and 'b':\n", product_ab)
else:
    print(f"\nArray 'a' and 'b' cannot be reshaped into square arrays because they do not contain a perfect square number of elements.")

# Display only the values that are less than 40 from array c
c_less_than_40 = c[c < 40]
print("\nValues less than 40 in array 'c':", c_less_than_40)

# Calculate and display the total of each row in array a
row_totals_a = np.sum(a.reshape(-1, 1), axis=1)
print("\nTotal of each row in array 'a':", row_totals_a)


Array 'a' and 'b' cannot be reshaped into square arrays because they do not contain a perfect square number of elements.

Values less than 40 in array 'c': [33 16 28 36 39 11 39 20 14 15]

Total of each row in array 'a': [42 27  5 33 24 31 16 38 41 19 31 25 45 33 33]


## Question 2

1.	Write a program that creates following numpy arrays and display
1.1.	Array with the values: 8,17,23,27
1.2.	Array with 10 zeros
1.3.	Array with the numbers from 1 to 10
1.4.	Array with the multiples of 3 up to 30
1.5.	Array that has 10 values from 1 to 30 and the difference between values is same
1.6.	Array with 10 random integer values from 0 to 100
1.7.	Two dimensional array with numbers from 1 to 9


In [6]:
# Array with the values: 8, 1, 7, 2, 3, 2, 7
array1 = np.array([8, 1, 7, 2, 3, 2, 7])
print("Array with values 8, 1, 7, 2, 3, 2, 7:\n", array1)

# Array with 10 zeros
array2 = np.zeros(10)
print("\nArray with 10 zeros:\n", array2)

# Array with the numbers from 1 to 10
array3 = np.arange(1, 11)
print("\nArray with numbers from 1 to 10:\n", array3)

# Array with the multiples of 3 up to 30
array4 = np.arange(3, 31, 3)
print("\nArray with multiples of 3 up to 30:\n", array4)

# Array that has 10 values from 1 to 30 and the difference between values is the same
array5 = np.linspace(1, 30, 10)
print("\nArray with 10 values from 1 to 30 (equal difference):\n", array5)

# Array with 10 random integer values from 0 to 100
array6 = np.random.randint(0, 101, 10)
print("\nArray with 10 random integer values from 0 to 100:\n", array6)

# Two-dimensional array with numbers from 1 to 9
array7 = np.arange(1, 10).reshape(3, 3)
print("\nTwo-dimensional array with numbers from 1 to 9:\n", array7)


Array with values 8, 1, 7, 2, 3, 2, 7:
 [8 1 7 2 3 2 7]

Array with 10 zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Array with numbers from 1 to 10:
 [ 1  2  3  4  5  6  7  8  9 10]

Array with multiples of 3 up to 30:
 [ 3  6  9 12 15 18 21 24 27 30]

Array with 10 values from 1 to 30 (equal difference):
 [ 1.          4.22222222  7.44444444 10.66666667 13.88888889 17.11111111
 20.33333333 23.55555556 26.77777778 30.        ]

Array with 10 random integer values from 0 to 100:
 [45 71 57 15 18 45 20 95 16 67]

Two-dimensional array with numbers from 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
